// Generated by CoffeeScript 1.6.3
(function() {
  var create_post, flush_games, games, list_games, list_get, nedb;

  nedb = require('nedb');

  games = new nedb();

  games.ensureIndex({
    fieldName: 'title',
    unique: true
  });

  list_games = function(request, response, next) {
    return games.find({
      finished: false
    }, function(err, docs) {
      var doc;
      request.games = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = docs.length; _i < _len; _i++) {
          doc = docs[_i];
          _results.push(parsegame(doc));
        }
        return _results;
      })();
      return next();
    });
  };

  flush_games = function(request, response, next) {
    return games.remove({
      finished: true
    }, function(err, removed) {
      request.admin.purged.games = removed;
      return next();
    });
  };

  exports.defines = {
    'list games': list_games,
    'flush games': flush_games
  };

  list_get = function(request, response) {
    var _ref;
    return response.render('games', {
      title: 'Games List - ',
      games: (_ref = request.games) != null ? _ref : {}
    });
  };

  create_post = function(request, response) {
    var _ref;
    return response.render('games', {
      title: 'Create Game - ',
      games: (_ref = request.games) != null ? _ref : {}
    });
  };

  exports.addroutes = function(router) {
    router.get('/games', 'verify nickname', 'list games', list_get);
    return router.post('/games/create', 'verify nickname', 'list games', create_post);
  };

}).call(this);
